### ISSUE TITLE
KotlinNullPointerException

### ISSUE THREAD

**Issue by venkatpantham-mi** [callstack/react-native-pager-view#323]
## Environment
"react-native-pager-view": "^5.1.2"
OnePlus 8T
Android 11 (SDK 30)

## Issue
`com.reactnativepagerview.PagerViewViewManager.createViewInstance`

```
kotlin.KotlinNullPointerException: 
  at com.reactnativepagerview.PagerViewViewManager.createViewInstance (PagerViewViewManager.kt:30)
  at com.reactnativepagerview.PagerViewViewManager.createViewInstance (PagerViewViewManager.kt:21)
  at com.facebook.react.uimanager.ViewManager.createViewInstance (ViewManager.java:139)
  at com.facebook.react.uimanager.ViewManager.createView (ViewManager.java:82)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.createView (NativeViewHierarchyManager.java:269)
  at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute (UIViewOperationQueue.java:179)
  at com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:773)
  at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:888)
  at com.facebook.react.uimanager.UIViewOperationQueue.access$2200 (UIViewOperationQueue.java:42)
  at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded (UIViewOperationQueue.java:846)
  at com.facebook.react.bridge.GuardedRunnable.run (GuardedRunnable.java:29)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7710)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:516)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)

```  
  This is the error I'm getting from the google play console

**Comment by efstathiosntonas** [comment]
Same here, it occured in several SDKs from 7 up to 11 and in several devices

**Comment by troZee** [comment]
Hello 👋 
Could you provide a reproducible example ? I am not able to reproduce it using a local example `https://github.com/callstack/react-native-pager-view/tree/master/example`

**Comment by fatiherdogan01** [comment]
[](url)
![Ekran Resmi 2021-04-17 12 53 12](https://user-images.githubusercontent.com/13077861/115108976-f5e2b000-9f7b-11eb-9279-9e6b5eea8b61.png)
Same here

**Comment by cojj90** [comment]
![image](https://user-images.githubusercontent.com/4283871/115181082-3a607e00-a12b-11eb-8aac-6dab57848185.png)

same here

**Comment by troZee** [comment]
Can anyone debug in your own code using android studio, why `reactContext.currentActivity` is not `FragmentActivity` ? and what kind of `Activity` is `reactContext.currentActivity` ? 

Line affected:
https://github.com/callstack/react-native-pager-view/blob/master/android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt#L30

**Comment by cojj90** [comment]
@troZee I found one reliable way to replicate this bug.

Have the pager render behind the Android permission request popup.

For me, when I start my app, it requests for an Android permission immediately. Behind the popup, I see my app rendering and it crashes as soon as it tries to render the pager stuff. If I dismiss (i.e. Allow or deny the permission) quick enough, it will not crash

**Comment by troZee** [comment]
@cojj90 thank you for an explanation. Could you provide a reproducible repository ? Or you can just clone this repo and add this case into an example. 

Maybe you should request permission using `useEffect` ? Maybe that will fix above issue ?

**Comment by KestasVenslauskas** [comment]
Having same crashes, I do not have any permission requests on my app.

**Comment by Kelvne** [comment]
@venkatpantham-mi Did you find any prior version that prevents this crash?

**Comment by enigmablue** [comment]
also getting this - but dont know how to replicate :/

**Comment by grit96** [comment]
I've also seen this issue in the Google Play Console on a few devices on Android 9 and 10.

![image](https://user-images.githubusercontent.com/3957608/117267091-d38ed480-ae4d-11eb-9175-4a0e0d903aa7.png)

**Comment by AymerZhang** [comment]
I resolve this problem. it's happened when i close the container of react native and jump to a component that contain pagerView(logical error).  It's all my faults , so  i  suggest check the react native code whether contains that case.

**Comment by cojj90** [comment]
> Can anyone debug in your own code using android studio, why `reactContext.currentActivity` is not `FragmentActivity` ? and what kind of `Activity` is `reactContext.currentActivity` ?
> 
> Line affected:
> https://github.com/callstack/react-native-pager-view/blob/master/android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt#L30

currentActivity is null :s

Seems to happen when app is rendering pager-view in the background

**Comment by troZee** [comment]
> > Can anyone debug in your own code using android studio, why `reactContext.currentActivity` is not `FragmentActivity` ? and what kind of `Activity` is `reactContext.currentActivity` ?
> > Line affected:
> > https://github.com/callstack/react-native-pager-view/blob/master/android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt#L30
> 
> currentActivity is null :s

Thank you for investigation @cojj90. It is impossible to create view without activity, bc adapter needs this activity as a dependency in the constructor. 

Probably it is related to this issue: 
https://stackoverflow.com/questions/45435450/getcurrentactivity-in-reactcontextbasejavamodule-returns-null

**Comment by thanakij** [comment]
Hi @troZee,

So it is like you are saying using Activity is a hard wall then.

According to the [doc](https://developer.android.com/reference/kotlin/androidx/viewpager2/adapter/FragmentStateAdapter#public-constructors), would other available constructors work?
For example, the one below seems promising as it has "LifeCycle" as one of parameters?

```
FragmentStateAdapter(@NonNull fragmentManager: FragmentManager, @NonNull lifecycle: Lifecycle)
```

**Comment by troZee** [comment]
> Hi @troZee,
> 
> So it is like you are saying using Activity is a hard wall then.
> 
> According to the [doc](https://developer.android.com/reference/kotlin/androidx/viewpager2/adapter/FragmentStateAdapter#public-constructors), would other available constructors work?
> For example, the one below seems promising as it has "LifeCycle" as one of parameters?
> 
> ```
> FragmentStateAdapter(@NonNull fragmentManager: FragmentManager, @NonNull lifecycle: Lifecycle)
> ```

Thank you for an investigation @thanakij. I think, it wont work, bc both parameters need an Activity, which is null. I don't know, why activity can be null ? @cojj90 said `Seems to happen when app is rendering pager-view in the background. `, but I was not able to reproduce that case. The second thing is, why activity is null, when app is in the background ? 

As you can see, there is lots of questions and without any reproducible code, I am not able to fix it.

**Comment by cojj90** [comment]
> As you can see, there is lots of questions and without any reproducible code, I am not able to fix it.

@troZee I'll provide a reproducible code when I get around to it! 

For now, as a workaround, we added an explicit check in JS to check for Android activity before rendering pager-view

**Comment by thanakij** [comment]
@cojj90 I am glad that this gets moving. :) By the way @troZee, if we can actually check null for Android activity from JS as prevention, then wouldn't this mean we can simply check null just right before [L30](https://github.com/callstack/react-native-pager-view/blob/master/android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt#L30) and quickly return from the method?

This can be done in one simple pull request and would prevent the crash reported by many for now.

---

Then we can move to think the next step which is "Will this actually be the proper way to handle the null case?"

What we know:
- Confirmed that Android activity can (and will) be null (due to several reasons.)

What I think:
- May relate to the nature of [Android's lifecycle](https://developer.android.com/guide/components/activities/activity-lifecycle) so that `onCreate`, ... and `onDestroy` would be called accordingly.

Next interesting thing to know:
- During the app's restoration process of Android, does it mean Android Native Modules like this lib would be re-initialized (via `createViewInstance`) as well?
- If yes, then actually checking null before L30 is not just a workaround but a solution.

**Comment by zholmes1** [comment]
Just received a report for this bug from a device running Android 6.0.1.

Happened directly on app launch (my main screen is a ViewPager). No permission check.

**Comment by troZee** [comment]
@cojj90 
> For now, as a workaround, we added an explicit check in JS to check for Android activity before rendering pager-view

Could you provide a code snippet of that solution ? I would like to take a look on it.

**Comment by troZee** [comment]
the fix has been released here: 
https://github.com/callstack/react-native-pager-view/releases/tag/v5.2.1

Please let me know, if everything is fine

**Comment by thanakij** [comment]
Hi @troZee, thank you for this 👍 

I am going to build an app update and publish it to Play Store. After majority of the users have updated the version, I will let you know if we actually see less number of crashes reported by Crashlytics.

**Comment by thanakij** [comment]
Good news! It has been about one week after I pushed an app update.
So far we longer see the crash!

**Comment by troZee** [comment]
great job @zabutok 🎉 ❤️

**Comment by YanisKondakov** [comment]
We still have the crash on production.

Packages versions:
```
"react-native": "0.64.0"
 "react-native-pager-view": "5.2.1"
 "react-native-tab-view": "3.0.1"
```
Hermes: true

![2021-06-23_14-17](https://user-images.githubusercontent.com/19660005/123087998-e1181200-d42d-11eb-8d4f-ec04289a8c57.png)

**Comment by zabutok** [comment]
> We still have the crash on production.
> 
> Packages versions:
> 
> ```
> "react-native": "0.64.0"
> "react-native-pager-view": "5.2.1"
> "react-native-tab-view": "3.0.1"
> ```
> 
> Hermes: true
> 
> ![2021-06-23_14-17](https://user-images.githubusercontent.com/19660005/123088184-1886be80-d42e-11eb-9692-4a5c13bd3541.png)

@YanisKondakov i think do you have two different version react-native-pager-view please try use resolution in your package.json for react-native-tab-view and @react-navigation/material-top-tabs maybe something else

**Comment by thanakij** [comment]
Hi @troZee @zabutok,

Although it is no longer crashing, now it sometimes renders nothing.

I have created a new issue #389.

**Comment by jcdhlzq** [comment]
@zabutok does your problem still exist in v5.4.9?

> > We still have the crash on production.
> > Packages versions:
> > ```
> > "react-native": "0.64.0"
> > "react-native-pager-view": "5.2.1"
> > "react-native-tab-view": "3.0.1"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hermes: true
> > ![2021-06-23_14-17](https://user-images.githubusercontent.com/19660005/123088184-1886be80-d42e-11eb-9692-4a5c13bd3541.png)
> 
> @YanisKondakov i think do you have two different version react-native-pager-view please try use resolution in your package.json for react-native-tab-view and @react-navigation/material-top-tabs maybe something else

does this problem still exist in v5.4.9?
