### ISSUE TITLE
RNCViewPager/RNCViewPagerComponentDescriptor.h file not found #812 how to fix this issue

### ISSUE THREAD

**Issue by vinamrahalgar** [callstack/react-native-pager-view#822]

**Comment by MrRefactor** [comment]
Could you provide more context and versions used?

**Comment by HunainHumail** [comment]
Having same issue in React Native 0.74 Enabling new architecture

**Comment by andresev** [comment]
Just got this issue right now.

**Comment by andresev** [comment]
So I was looking through the latest commits on Apr 24, some changes were made to the package.json and updated version to 6.3.1.

I reverted back to 6.3.0, and it works. In case anyone had it working before.

**Comment by vinamrahalgar** [comment]
"react-native-pager-view": "^6.2.3" - I am using this version. I removed the auto upgrade the ran the project it works but very inconsistent. Facing it again and again. Didn't get permanent solution

**Comment by sriharsha-y** [comment]
Couple of things which I noticed
- package.json doesn't include "Common" folder so npm package missing these cpp files.
- iOS podspec doesn't have proper subspec to include these cpp files like the one which we have on v7.0-rc2
Not sure what else is missing on Android.

**Comment by vinamrahalgar** [comment]
Any idea  on how to fix this?

**Comment by sriharsha-y** [comment]
@vinamrahalgar we made a patch <script src="https://gist.github.com/sriharsha-y/1e847547c42254b8b33421d4edcc24f9.js"></script>
This works but not sure whether it's right way to do the stuff....

**Comment by vinamrahalgar** [comment]
thanks

**Comment by Jackmekiss** [comment]
Same here....

**Comment by vipom** [comment]
> Couple of things which I noticed in 6.3.1
> 
> * package.json doesn't include "Common" folder so npm package missing these cpp files.
> * iOS podspec doesn't have proper subspec to include these cpp files like the one which we have on v7.0-rc2
>   Not sure what else is missing on Android.

All of this seems to have been fixed by merging #830 into master (but we need a new release).

**Comment by MrRefactor** [comment]
Fixed in 6.3.2 release

**Comment by ghoudi01** [comment]
any solution for android

**Comment by Shahrukh0396** [comment]
@MrRefactor still facing this issue on v6.3.2 using react native 0.74.2, any guess?

**Comment by MrRefactor** [comment]
> @MrRefactor still facing this issue on v6.3.2 using react native 0.74.2, any guess?

Please use the latest release which is `v6.3.3`

**Comment by sebkes** [comment]
I still have this issue when using RN 0.74.2 and v6.3.3

**Comment by hapney** [comment]
`Console > Clear Console` along with closing and reopening Xcode resolved this for me.

**Comment by Dat-Mobile** [comment]
<img width="466" alt="Image" src="https://github.com/user-attachments/assets/1e1c5c5b-7911-461f-a1b1-752c44f6a888" />

The issue is gone when I downgrade from `7.0.0-rc.2` to `6.6.1`. Notice that `Removing React-Codegen` red line in the pod install. Then the app was built successfully

But version `6.6.1` still has issue that block the scroll when `TabView` inside `ScrollView` (#722)
